# Generated by Django 5.1.2 on 2024-11-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colectivero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropago',
            old_name='trabajado',
            new_name='pago_realizado',
        ),
        migrations.AddField(
            model_name='registropago',
            name='trabajo_status',
            field=models.CharField(choices=[('worked', 'Trabajó'), ('not_worked', 'No Trabajó')], default='not_worked', max_length=20),
        ),
        migrations.AlterField(
            model_name='registropago',
            name='tarifa_pagada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
